import type { Metadata } from "next";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Heart, Shield, Sparkles, Zap } from "lucide-react";

export const metadata: Metadata = {
  title: "About",
  description:
    "Learn about ChibiDrop — how we generate cute chibi art daily, why it's free, and how you can use it.",
};

const FAQ_ITEMS = [
  {
    question: "Is this really free?",
    answer:
      "Yes! All chibi art generated by ChibiDrop is completely free to download and use for any purpose — personal, commercial, educational, you name it. No attribution required, no strings attached.",
  },
  {
    question: "How are the chibis generated?",
    answer:
      "We use AI image generation models (like DALL-E 3) to create cute chibi-style artwork. Our daily pipeline picks themes, crafts prompts, generates images, and uploads them to the gallery. Some items also get animated using video generation models.",
  },
  {
    question: "Can I use these for commercial projects?",
    answer:
      "Absolutely. All content is public domain. Use it for merchandise, apps, websites, presentations, social media, or anything else you can think of.",
  },
  {
    question: "Do I need to give credit?",
    answer:
      "No attribution is required, but we appreciate it! If you do share, feel free to mention ChibiDrop — it helps others discover the project.",
  },
  {
    question: "How often are new chibis added?",
    answer:
      "Every day at 9 AM UTC, our automated pipeline generates 4 new chibi items. Some of them also get animated versions. Check back daily for fresh content!",
  },
  {
    question: "Can I request specific themes?",
    answer:
      "Yes! Use the 'Propose an idea' page to submit theme suggestions. We review proposals and incorporate the best ones into our daily generation queue.",
  },
  {
    question: "What's the tech stack?",
    answer:
      "ChibiDrop is built with Next.js 16, TypeScript, Tailwind CSS, shadcn/ui, Drizzle ORM, Neon Postgres, Cloudflare R2 for storage, and Vercel for hosting. The AI pipeline uses OpenAI and Fal.ai APIs.",
  },
  {
    question: "Is this open source?",
    answer:
      "The codebase is private for now, but the generated content is completely open. We may open-source the project in the future.",
  },
];

export default function AboutPage() {
  return (
    <div className="container-page py-12 sm:py-16">
      <div className="mx-auto max-w-3xl">
        {/* Hero */}
        <div className="mb-12 text-center">
          <Badge variant="secondary" className="mb-4">
            <Heart className="mr-1.5 h-3.5 w-3.5" />
            Made with love
          </Badge>
          <h1 className="mb-4 text-4xl font-bold tracking-tight sm:text-5xl">
            About ChibiDrop
          </h1>
          <p className="text-muted-foreground text-lg">
            Cute chibi art, generated daily by AI, free for everyone to use.
          </p>
        </div>

        {/* What is ChibiDrop */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="text-primary h-5 w-5" />
              What is ChibiDrop?
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              ChibiDrop is an experiment in automated AI art generation. Every day, our
              pipeline creates 4 new chibi-style images — cute, cartoonish characters with
              big heads and expressive faces. Some of them also get animated versions.
            </p>
            <p>
              The project started as a fun side project to explore AI image generation,
              but we quickly realized the output could be useful for others. So we made it
              public and free.
            </p>
            <p>
              Whether you need avatars, illustrations, stickers, or just some cute art to
              brighten your day, ChibiDrop has you covered.
            </p>
          </CardContent>
        </Card>

        {/* How it works */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Zap className="text-primary h-5 w-5" />
              How it works
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>Our pipeline runs daily at 9 AM UTC:</p>
            <ol className="list-inside list-decimal space-y-2">
              <li>
                <strong>Theme selection:</strong> We pick 4 themes from a mix of curated
                ideas and user proposals.
              </li>
              <li>
                <strong>Prompt expansion:</strong> GPT-5.4-mini expands each theme into a
                detailed image generation prompt.
              </li>
              <li>
                <strong>Image generation:</strong> OpenAI&apos;s image models create the
                chibi artwork.
              </li>
              <li>
                <strong>Metadata generation:</strong> AI generates titles, descriptions,
                and tags for each item.
              </li>
              <li>
                <strong>Upload:</strong> Images are uploaded to Cloudflare R2 for fast,
                global delivery.
              </li>
              <li>
                <strong>Animation (optional):</strong> Some items get animated using
                Fal.ai&apos;s video generation models.
              </li>
              <li>
                <strong>Publish:</strong> Everything goes live in the gallery for you to
                browse and download.
              </li>
            </ol>
          </CardContent>
        </Card>

        {/* Free to use */}
        <Card className="border-primary/20 bg-primary/5 mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="text-primary h-5 w-5" />
              Free to use
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              All content generated by ChibiDrop is{" "}
              <strong>completely free to use</strong> for any purpose:
            </p>
            <ul className="list-inside list-disc space-y-2">
              <li>Personal projects</li>
              <li>Commercial products</li>
              <li>Apps and websites</li>
              <li>Social media content</li>
              <li>Educational materials</li>
              <li>Merchandise and print</li>
            </ul>
            <p>
              <strong>No attribution required.</strong> No license restrictions. No hidden
              fees. Download and use however you like.
            </p>
            <p className="text-muted-foreground text-sm">
              Note: While we strive for quality, AI-generated content can sometimes be
              imperfect. Use at your own discretion.
            </p>
          </CardContent>
        </Card>

        {/* FAQ */}
        <div className="mb-8">
          <h2 className="mb-6 text-2xl font-semibold tracking-tight sm:text-3xl">
            Frequently asked questions
          </h2>
          <div className="space-y-4">
            {FAQ_ITEMS.map((item, index) => (
              <Card key={index}>
                <CardHeader>
                  <CardTitle className="text-lg">{item.question}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">{item.answer}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* CTA */}
        <Card className="text-center">
          <CardContent className="pt-6">
            <p className="mb-4 text-lg">
              Ready to explore? Check out the gallery or propose your own ideas.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Link
                href="/gallery"
                className="bg-primary text-primary-foreground hover:bg-primary/90 inline-flex items-center rounded-md px-6 py-3 text-sm font-medium shadow transition-colors"
              >
                Browse gallery
              </Link>
              <Link
                href="/propose"
                className="border-input bg-background hover:bg-accent hover:text-accent-foreground inline-flex items-center rounded-md border px-6 py-3 text-sm font-medium shadow-sm transition-colors"
              >
                Propose an idea
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
